"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowRight, LockKeyhole, Play, Pause, SkipForward, RotateCcw, FileText, MessagesSquare, Calculator, Search, ShieldCheck, Workflow, Circle, ChevronRight, Check, Terminal, GitBranch, X, ArrowUpRight } from "lucide-react";
import { SidebarProvider, Sidebar, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton } from "@/components/ui/sidebar";
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from "@/components/ui/table";
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { cases,type Role } from "@/lib/hearing/cases";
import { format,signed,type Evidence } from "@/lib/hearing/ledger";
import { deriveState,deriveConclusion } from "@/lib/hearing/machine";
import { useHearing } from "@/lib/hearing/store";
import { registerHearingTools } from "@/lib/hearing/webmcp";
const roles=[{id:"host",name:"主持",task:"分派 · 收束",icon:Workflow},{id:"accountant",name:"核算",task:"算数 · 勾稽",icon:Calculator},{id:"investigator",name:"调查",task:"查证 · 补证",icon:Search},{id:"reviewer",name:"复核",task:"质疑 · 把关",icon:ShieldCheck}];
const roleOf=(id:Role)=>roles.find(r=>r.id===id)!;
const phaseLabels={idle:"待会审",dispatched:"已分派",investigating:"查证中",reviewing:"复核中",supplementing:"补查中",recalculating:"重算中",concluded:"已形成结论"};
export default function Home(){
 const p=useHearing();const c=cases[p.caseIndex];
 const state=useMemo(()=>deriveState(c,p.head,p.done),[c,p.head,p.done]);
 const conclusion=useMemo(()=>p.done?deriveConclusion(c,state):null,[c,state,p.done]);
 const [doc,setDoc]=useState<Evidence|null>(null);const [reduceMotion,setReduceMotion]=useState(false);
 const scrollRef=useRef<HTMLDivElement>(null),mainRef=useRef<HTMLButtonElement>(null),docOpenerRef=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{const mq=matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setReduceMotion(mq.matches);update();mq.addEventListener("change",update);return()=>mq.removeEventListener("change",update)},[]);
 useEffect(()=>{const caseParam=new URLSearchParams(location.search).get("case");if(caseParam==="02")useHearing.getState().select(1);return registerHearingTools();},[]);
 useEffect(()=>{if(!p.running)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();useHearing.getState().tick(now-last);last=now;},50);return()=>clearInterval(timer)},[p.running,p.caseIndex]);
 const current=p.head>=0?c.beats[p.head]:null;
 const typed=current?(reduceMotion||p.done?current.text.length:Math.floor(p.elapsed/19)):0;
 useEffect(()=>{const element=scrollRef.current;if(element)element.scrollTop=element.scrollHeight},[p.head,typed,p.caseIndex]);
 const duration=c.beats.reduce((v,b)=>v+b.duration,0);
 const progress=p.done?100:Math.min(100,(c.beats.slice(0,Math.max(0,p.head)).reduce((v,b)=>v+b.duration,0)+p.elapsed)/duration*100);
 const selectCase=(index:number)=>{setDoc(null);p.select(index);const url=new URL(location.href);url.searchParams.set("case",cases[index].id);history.replaceState(null,"",url);};
 const openDoc=(e:Evidence,button:HTMLButtonElement)=>{docOpenerRef.current=button;setDoc(e)};
 const currentStatus=p.head<0?"待会审":p.done?"已形成结论":!p.running?"已暂停":phaseLabels[state.phase];
 return <>
 <header className="topbar"><div className="brand"><div className="brand-mark" aria-hidden="true">审</div><div className="brand-name">费用会审室</div><i className="brand-line"/><span className="brand-subtitle">用证据，把结论改掉。</span></div><div className="demo-pill">交互演示 <b>·</b> 合成数据 <b>·</b> 未连接 Grok</div></header>
 <nav className="mobile-nav" aria-label="切换会审案件">{cases.map((item,i)=><button key={item.id} onClick={()=>selectCase(i)} className={p.caseIndex===i?"selected":""} aria-current={p.caseIndex===i?"page":undefined}><span className="mono">{item.id}</span>　{item.title}</button>)}</nav>
 <SidebarProvider className="app-frame"><Sidebar collapsible="none" className="case-sidebar"><div className="side-heading">本月会审 <span>02</span></div><div className="side-date mono">2026 / 08</div><SidebarContent><nav aria-label="会审案件"><SidebarMenu>{cases.map((item,i)=><SidebarMenuItem key={item.id}><SidebarMenuButton className="case-nav" isActive={p.caseIndex===i} aria-current={p.caseIndex===i?"page":undefined} onClick={()=>selectCase(i)}><div className="case-number mono">CASE {item.id}{p.caseIndex===i&&<ChevronRight size={13}/>}</div><div className="case-name">{item.title}</div><div className="case-meta">{item.department} · {item.topic}</div></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></nav></SidebarContent><SidebarFooter className="side-footer"><strong>一条差异 / 四个 Bot</strong><span>一份有依据的结论</span></SidebarFooter></Sidebar>
 <main className="workspace">
 <div className="breadcrumb">{c.department} <span className="slash">/</span> <span className="mono">EXP-202608-{c.id}</span><span className="status-badge" aria-live="polite">{currentStatus}</span></div>
 <div className="title-row"><h1>{c.title}</h1><span className="case-tag mono">CASE {c.id} / 02</span></div>
 <section className="claim-card" aria-label="待核主张"><span className="quote-mark" aria-hidden="true">“</span><div><div className="claim-label">待核主张 <span>部门经营解释</span></div><p className="claim-text">{c.claim}</p><div className="claim-foot">一句解释，四个角色，一起核实。</div></div></section>
 <div className="roles" aria-label="四角色协作进度">{roles.map(r=>{const active=current?.role===r.id&&!p.done;const participated=c.beats.slice(0,p.head+1).some(b=>b.role===r.id);return <div className={`role ${active?"active":""}`} key={r.id} aria-label={`${r.name}，${active?"当前发言":p.done?"已完成":participated?"等待交接":"待命"}`}><div className="avatar"><r.icon size={17}/></div><div><div className="role-name">{r.name}</div><div className="role-desc">{active?(!p.running?"发言已暂停":"正在发言"):r.task}</div></div>{p.done?<Check size={12} className="role-state"/>:<Circle size={6} fill={active?"currentColor":"none"} className="role-state"/>}</div>})}</div>
 <div className="work-grid">
 <section className="panel transcript-panel" aria-label="协作记录"><div className="panel-head"><div className="panel-heading"><MessagesSquare size={16}/>协作记录</div><span className="panel-note">{p.head<0?"四角色 · 同案协作":`补查 ${state.rounds} / 2 轮`}</span></div><Progress value={progress} aria-label="会审播放进度" className="progress-line"/>
 {p.head<0?<div className="empty-stage"><div className="empty-symbol"><MessagesSquare size={28}/></div><h2>让解释，经过一次会审。</h2><p>核对差异、追查证据、交叉复核。<br/>四个角色就位，等待开始。</p><div className="empty-line">分派 → 查证 → 复核 → 结论</div></div>:<div className="transcript" ref={scrollRef} tabIndex={0} aria-label="会审发言，可滚动查看历史">{c.beats.slice(0,p.head+1).map((beat,index)=>{const r=roleOf(beat.role);const latest=index===p.head;const text=latest?beat.text.slice(0,typed):beat.text;const complete=!latest||text.length===beat.text.length;return <article className={`message ${latest?"current":""}`} key={`${c.id}-${index}`}><div className="avatar"><r.icon size={16}/></div><div className="message-content"><div className="message-meta">{r.name}<span>Bot</span><span className="mono" style={{marginLeft:"auto"}}>{String(index+1).padStart(2,"0")}</span>{latest&&!p.running&&!p.done&&<small className="paused-chip">暂停</small>}</div><p className="message-text" aria-label={beat.text}><span aria-hidden="true" className={!complete?"cursor":""}>{text}</span></p>{complete&&<><div className="message-tool"><Terminal size={11}/>{beat.tool}</div>{beat.handoff&&<div className="message-handoff"><GitBranch size={11}/>{beat.handoff}</div>}</>}</div></article>})}</div>}
 {p.done&&<button className="conclusion-inline" onClick={()=>p.setConclusion(true)}><span><Check size={13} style={{display:"inline",marginRight:6}}/>会审完成 · 结论待人确认</span><ArrowUpRight size={15}/></button>}
 </section>
 <div className="evidence-column">
 <section className="panel" aria-label="金额与证据"><div className="panel-head"><div className="panel-heading">金额与证据</div><span className="panel-note">人民币 · 万元</span></div><div className="ledger-body"><div className="money-grid" data-testid="book-values">{[["账面预算",format(c.book.bookBudget)],["账面实际",format(c.book.bookActual)],["账面差异",signed(c.book.bookVariance)]].map(([name,value],i)=><div className="money-item" key={name}><div className="money-label">{name}</div><div className={`money-value ${i===2?"accent":""}`}>{value}</div></div>)}</div><Table className="ledger-table"><TableHeader><TableRow>{["科目","预算","实际","差异"].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{c.book.rows.map(row=><TableRow key={row.name}><TableCell>{row.name}</TableCell><TableCell>{format(row.budget)}</TableCell><TableCell>{format(row.actual)}</TableCell><TableCell>{signed(row.actual-row.budget)}</TableCell></TableRow>)}<TableRow className="total"><TableCell>合计</TableCell><TableCell>{format(c.book.bookBudget)}</TableCell><TableCell>{format(c.book.bookActual)}</TableCell><TableCell>{signed(c.book.bookVariance)}</TableCell></TableRow></TableBody></Table><div className="table-foot"><LockKeyhole size={11}/>账面快照已锁定 · 会审仅调整管理口径</div>
 {state.adjusted&&<div className="mgmt-card" data-testid="management-values"><div className="mgmt-title"><span>管理口径对照</span><span>{c.department} · 8 月</span></div><div className="mgmt-numbers mono"><span className="before">{signed(c.book.bookVariance)}</span><ArrowRight size={18}/><strong>{signed(state.mgmtVariance)}</strong><span style={{fontSize:12}}>万元</span></div><div className="mgmt-description">{c.id==="01"?`销售 −${format(c.amount)} · 客服 +${format(c.amount)} · 公司本案费用仍为 ${format(c.book.bookActual)} 万`:`8 月 +${format(c.amount)} · 9 月 −${format(c.amount)} · 全年合计不变`}<br/>管理实际 {format(state.mgmtActual)} 万 · 账面原值未变</div></div>}
 </div></section>
 <section className="panel evidence-panel" aria-label="原始材料"><div className="panel-head"><div className="panel-heading">原始材料</div><span className="panel-note">已取得 {state.evidence.length} / {c.evidence.length}</span></div><div className="evidence-list">{c.evidence.map(e=>{const available=e.unlock<=p.head;return <button className="evidence-row" key={e.id} disabled={!available} onClick={event=>openDoc(e,event.currentTarget)} aria-label={`${e.name}，${available?e.status==="unsigned"?"未签字草稿，查看详情":"已取得，查看详情":"待补充"}`}><div className="file-icon"><FileText size={15}/></div><div className="file-text"><strong>{e.name}</strong><small>{available?e.summary:"待调查核实"}</small></div><span className={`evidence-badge ${available?e.status==="unsigned"?"draft":"ready":""}`}>{available?e.status==="unsigned"?"未签字":"已取得":"待补充"}</span>{available&&<ChevronRight size={12} color="#b1a3bc"/>}</button>})}</div></section>
 </div></div>
 {p.error&&<p role="alert" className="action-error">{p.error}。会审已停止，请重放。</p>}
 <div className="controls"><span className="control-status">{p.head<0?<><LockKeyhole size={12}/>账面原值保留，管理口径可追溯</>:<><span className="mono">{p.done?"09":String(p.head+1).padStart(2,"0")} / 09</span><span>·</span>{p.done?"会审完成":p.running?"自动播放中":"已暂停，可单步推进"}</>}</span><div className="control-buttons">{p.head>=0&&<button className="quiet-btn" onClick={p.replay} aria-label="重放当前案件"><RotateCcw size={14}/><span>重放</span></button>}{p.running?<button className="quiet-btn" onClick={p.pause}><Pause size={14}/>暂停</button>:!p.done&&<button className="quiet-btn" onClick={p.step}><SkipForward size={14}/>单步</button>}<button ref={mainRef} className="primary-btn" disabled={p.running} onClick={p.play}>{p.done?<><FileText size={14}/>查看结论卡</>:p.running?<><span className="mono">{Math.round(progress)}%</span> 会审中…</>:<><Play size={14}/>{p.head<0?"开始会审":"继续会审"}<ArrowRight size={14}/></>}</button></div></div>
 <p className="footer-note">合成数据用于交互演示 · {p.head<0?"自动播放约 40 秒 · ":""}会审结论待人工确认</p>
 </main></SidebarProvider>
 <Dialog open={p.showConclusion} onOpenChange={p.setConclusion}><DialogContent className="decision-dialog" showCloseButton={false} onCloseAutoFocus={event=>{event.preventDefault();mainRef.current?.focus()}}>{conclusion&&<><DialogClose className="absolute right-5 top-5 p-1" aria-label="关闭结论卡"><X size={18}/></DialogClose><div><div className="dialog-kicker mono">HEARING CONCLUSION / CASE {c.id}</div><DialogTitle>这一次，解释被证据改写。</DialogTitle><DialogDescription className="mt-2">{c.department} · 2026 年 8 月 · 结论待人工确认</DialogDescription></div><section className="decision-section"><h3>01　原解释</h3><div className="original-claim"><span className="verdict">{conclusion.verdict}</span><p>{conclusion.original}</p></div></section><section className="decision-section"><h3>02　修正解释</h3><p>{conclusion.correction}</p></section><section className="decision-section"><h3>03　金额桥 <span style={{marginLeft:"auto"}}>人民币 · 万元</span></h3><div className="decision-bridge"><div><strong>{conclusion.before}</strong><small>账面预算差异</small></div><ArrowRight size={18}/><div><strong>{conclusion.adjustment}</strong><small>{c.id==="01"?"分摊给客服":"恢复本期费用"}</small></div><ArrowRight size={18}/><div><strong>{conclusion.after}</strong><small>管理口径差异</small></div></div><div className="decision-foot">{conclusion.balanceText}<br/>账面 {format(c.book.bookBudget)} / {format(c.book.bookActual)} / {signed(c.book.bookVariance)} 保持不变。</div></section><section className="decision-section"><h3>04　证据链 <span style={{marginLeft:"auto",fontSize:11}}>点击查看原始材料</span></h3><div className="chain">{state.evidence.map(e=><button key={e.id} onClick={event=>openDoc(e,event.currentTarget)}>{e.name}{e.status==="unsigned"?" · 未签字":""}</button>)}</div></section><section className="decision-section unresolved"><h3>05　未决项</h3><p>{conclusion.unresolved}</p></section><DialogClose className="primary-btn" style={{width:"100%"}}>返回会审记录<ArrowRight size={14}/></DialogClose></>}</DialogContent></Dialog>
 <Dialog open={!!doc} onOpenChange={open=>{if(!open)setDoc(null)}}><DialogContent className="decision-dialog" showCloseButton={false} onCloseAutoFocus={event=>{event.preventDefault();docOpenerRef.current?.focus()}}>{doc&&<><DialogClose className="absolute right-5 top-5 p-1" aria-label="关闭材料"><X size={18}/></DialogClose><div><div className="dialog-kicker mono">EVIDENCE / {doc.id}</div><DialogTitle>{doc.name}</DialogTitle><DialogDescription className="mt-2">{doc.summary}</DialogDescription></div><div className="document-content">{doc.body}</div><div className="document-meta"><FileText size={14}/>合成材料 · 仅用于演示</div><DialogClose className="quiet-btn">返回会审</DialogClose></>}</DialogContent></Dialog>
 </>;
}
